
[global]
remove_todos = false
remove_fixme = false
remove_docs = false
preserve_patterns = ["IMPORTANT", "NOTE", "WARNING"]
use_default_ignores = true
respect_gitignore = true


[languages.hare]
name = "Hare"
extensions = ["ha"]
comment_nodes = ["comment"]
preserve_patterns = ["TODO", "FIXME"]

[languages.crystal]
name = "Crystal"
extensions = ["cr"]
comment_nodes = ["comment"]
preserve_patterns = ["TODO", "FIXME", "ameba:"]

[languages.d]
name = "D"
extensions = ["d"]
comment_nodes = ["comment", "block_comment"]
doc_comment_nodes = ["block_comment"]
preserve_patterns = ["TODO", "FIXME"]

[languages.racket]
name = "Racket"
extensions = ["rkt", "rktl"]
comment_nodes = ["comment", "block_comment"]
preserve_patterns = ["TODO", "FIXME"]

[languages.solidity]
name = "Solidity"
extensions = ["sol"]
comment_nodes = ["comment"]
doc_comment_nodes = ["comment"]
preserve_patterns = ["TODO", "FIXME", "slither-disable"]

[languages.mojo]
name = "Mojo"
extensions = ["mojo"]
comment_nodes = ["comment"]
preserve_patterns = ["TODO", "FIXME"]


[languages.python]
name = "Python"
extensions = ["py", "pyw", "pyi"]
comment_nodes = ["comment"]
doc_comment_nodes = ["string"]
preserve_patterns = ["mypy:", "type:", "noqa:", "pragma:", "pylint:"]
remove_docs = true


[patterns."vendor/**/*"]
remove_todos = false
remove_fixme = false
remove_docs = false

[patterns."**/*.generated.*"]
remove_docs = true
remove_todos = true
remove_fixme = true
preserve_patterns = []
