
[global]
remove_todos = false
remove_fixme = false

[languages.hare]
name = "Hare"
extensions = ["ha"]
comment_nodes = ["comment"]

[languages.crystal]
name = "Crystal"
extensions = ["cr"]
comment_nodes = ["comment"]

[languages.python]
name = "Python"
extensions = ["py", "pyw", "pyi"]
comment_nodes = ["comment"]
preserve_patterns = ["noqa:", "type:", "mypy:"]
remove_docs = true
